### ISSUE TITLE
Rotating symbol on cancel button when hover in settings menu

### ISSUE THREAD

**Issue by masterwishx** [nutdotnet/WinNUT-Client#103]
installe latest version.
i have Rotating symbol on cancel button when hover in settings menu.

its not captured by screenshot , but meaned this cancel button : 
![image](https://github.com/nutdotnet/WinNUT-Client/assets/28630321/9afff2a8-6494-413c-9c51-3c07af417904)

**Comment by gbakeman** [comment]
Hi @masterwishx ,

This doesn't sound like something WinNUT would do... could you please find a way to capture an image of this icon?

**Comment by masterwishx** [comment]
> Hi @masterwishx ,
> 
> This doesn't sound like something WinNUT would do... could you please find a way to capture an image of this symbol?

![20231008_172234](https://github.com/nutdotnet/WinNUT-Client/assets/28630321/70929f21-3ba6-4b75-b45e-b0b444246e2d)

**Comment by gbakeman** [comment]
Sorry, I completely misunderstood what you meant. You're totally right, the cursor turns into the waiting/spinning circle cursor when I hover over my Cancel button. It looks like the Cancel button mistakenly has the `Cursor` property set to `WaitCursor` when I think it should be `Default`.

I'm currently working on a Preferences GUI replacement/upgrade in #102, so unless this is affecting program functionality, then go ahead and subscribe to that issue and I'll close this one in the meantime. Does this sound good?

**Comment by masterwishx** [comment]
Sure, I'm happy this app have been updating, I was using old version 2.0, only yesterday found this new version
