### ISSUE TITLE
Unable to exit when Close to tray and Minimize to tray are enabled

### ISSUE THREAD

**Issue by masterwishx** [nutdotnet/WinNUT-Client#105]
cant exit from app . nothing happening. only can exit by kill app from Ctrl+Alt+del menu
When press exit on icon :   

![image](https://github.com/nutdotnet/WinNUT-Client/assets/28630321/a5f0b754-508d-4aab-87fc-5680b2d454ce)

or when press Exit in App :  

![image](https://github.com/nutdotnet/WinNUT-Client/assets/28630321/06aa4fbe-89ec-490f-bcdc-d42ea5793704)

**Comment by masterwishx** [comment]
i found that exit by mistake ,take function of close to tray .
if i disable function close to tray in menu in settings, then exit working normal . i can exit from program.

![image](https://github.com/nutdotnet/WinNUT-Client/assets/28630321/b958554c-06ed-45e2-84ae-fbbd9a5b7568)

**Comment by masterwishx** [comment]
When i disable close to systray from menu and can exit:

![image](https://github.com/nutdotnet/WinNUT-Client/assets/28630321/2562111b-0775-4f96-ac72-a79f596e9c0a)

**Comment by UltrashRicco** [comment]
Same behaviour here, thank you for the tip consisting in NOT checking "close to tray", at least I can close Winnut if necessary, without having to kill the process.

The expected behaviour would be that when right-clicking on the tray icon and selecting "exit", Winnut should actually exit. Currently, it would appear that it keeps minimizing to the tray.

Thanks!

**Comment by gbakeman** [comment]
Hi all,

Another quick fix for this one. After applying it, exiting seems to work normally now. You can try a debug build [here ](https://github.com/nutdotnet/WinNUT-Client/actions/runs/6525104308?pr=108) once it finishes building, and I'm planning on making this a part of the next pre-release.

**Comment by UltrashRicco** [comment]
@gbakeman I tested the build and it does work as expected now, thank you! :)

**Comment by gbakeman** [comment]
Excellent, thank you for the feedback. I'll merge this and hopefully have a release out today.

**Comment by masterwishx** [comment]
Thanks for fixing this and auto reconnect bugs. 

Also after update I saw Logs folder moved to program folder instead in AppData/Roaming folder.

**Comment by gbakeman** [comment]
> Thanks for fixing this and auto reconnect bugs.
> 
> Also after update I saw Logs folder moved to program folder instead in AppData/Roaming folder.

I noticed that, too. :( I think I may have broken something with the new build configuration. You can track a fix in #110

**Comment by gbakeman** [comment]
@masterwishx I wrote up an explanation in the other bug, hope that answers your question.
