### ISSUE TITLE
LogFile controls are disabled when the Create LogFile option is on

### ISSUE THREAD

**Issue by gbakeman** [nutdotnet/WinNUT-Client#142]
![image](https://github.com/nutdotnet/WinNUT-Client/assets/842942/6b5d6d86-536e-4a78-9b13-249e91caf3a0)

**WinNUT Version:** 2.3.8834
**Windows OS Version:** Windows 11

**Describe the bug**
LogFile management controls in the Preferences window are disabled, despite logging apparently being enabled.

In addition; it would be nice to understand why log files are being created in the Roaming folder, while config files are going in the Local folder.

**Comment by masterwishx** [comment]
Have also in in roaming, also I think when set to info, no logs enabled while it's enabled in setting. But when change to debug then it's enabling the log

**Comment by masterwishx** [comment]
Just checked now , it was info and not enabled but enabled in setting .
1. set to debug then apply. (still shown as disabled)
2. closed app (its minimized to tray (by settings) )
3. opened again - its shown as enabled now.
4. changed to info then apply - its enabled now

**Comment by masterwishx** [comment]
but if i close app ,then open -  its disabled again

**Comment by gbakeman** [comment]
@masterwishx I've just made some changes with @MaxMadcc and we think the problem has been fixed now. If you have the time, please download a debug build from the linked pull request, and I think I can have another release out soon. Thank you for your patience!
