### ISSUE TITLE
Increasing battery max in Calibration extends the gauge instead of adjusting scale.

### ISSUE THREAD

**Issue by hugalafutro** [nutdotnet/WinNUT-Client#18]
**WinNUT Version:** v2.1.7740.35837
**Windows OS Version:** 11 x64

**Describe the bug**
I increased the max to 28 as my charged battery sits at around 27.1 and expected the gauge to remain same size and the data on it to "shrink", instead the gauge grew a new notch triggering my imagined ocd how it's all uneven now.

**To Reproduce**
1. Go to 'Settings/Calibration'
2. Increase Battery Max to 28
3. ???

**Expected behavior**
The gauge should not change, instead the scale of the data on it should.

**Screenshots**
![image](https://user-images.githubusercontent.com/30209689/183416374-9b72395d-ef20-46f5-b989-d8432757f01f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 x64 Version 21H2, Build 22000.832, Windows Feature Experience Pack 1000.22000.832.0

**Comment by hugalafutro** [comment]
I didn't know the repo moved here, I'll see if it happens with the latest version from here when I get home from work.

**Comment by gbakeman** [comment]
I suspect this is still an issue, but thank you for checking anyways. It may be a bug in AGauge but I will try to take a look at this when some of the other crash bugs are fixed.

**Comment by gbakeman** [comment]
Just want to update you. I've taken a dive into this issue, and only managed to clean up some code. It looks like the bug exists somewhere in the drawing code of the gauge, but it's a little beyond me at the moment. I was able to get the gauge to draw correctly while tweaking min and max values, I wonder if it may help if you bump up the minimum battery voltage?

**Comment by hugalafutro** [comment]
tweaking the value has some effect, but it only disappears when I set min to 20:
![image](https://user-images.githubusercontent.com/30209689/201516537-29cddd9e-2e79-41cc-918a-19d42ce12e51.png)

19 and lower makes it look like this:
![image](https://user-images.githubusercontent.com/30209689/201516546-6968758b-d055-451f-9a0d-ab307bc83f7c.png)

**Comment by gbakeman** [comment]
Just an update and more of a note to myself after looking into this more: It seems like this problem occurs when `ScaleLinesMajorStepValue` is an odd number of 3 or higher, and the Min or MaxValue is an odd number. Continuing the search.

**Comment by hugalafutro** [comment]
Hi I've compltely forgot about this issue, but it the latest prerelease ([2.2.8693](https://github.com/nutdotnet/WinNUT-Client/releases/tag/v2.2.8693)) it seems to work ok:
![image](https://github.com/nutdotnet/WinNUT-Client/assets/30209689/a7df3f6e-d018-43e1-8a9f-69bf0db566fa)

**Comment by gbakeman** [comment]
I can't imagine what would've done it; I've spent several hours already trying to get to the bottom of the issue, and could have sworn it was still there. When I jump back into this project, let me test it some more to see if I can't reproduce it.

**Comment by gbakeman** [comment]
Thanks for your patience on this one, I believe it's fixed now! To summarize, the issue occurs when someone tries to enter a Min or MaxValue which is not divisible by the number of spaces between a major tick mark on the gauge. As far as WinNUT is concerned, as long as you keep the total gauge range (Min and Max) an even number, it should be fine. To help with this, I've made the gauge only display one major tick mark range when an invalid number is entered, like below:

![image](https://github.com/user-attachments/assets/1aef00a7-791f-4b2f-939c-cba1584376ba)

Hope this helps!

**Comment by hugalafutro** [comment]
There was no rush, thanks for finding the time to fix a cosmetic issue!
