### ISSUE TITLE
APC UPS not showing values

### ISSUE THREAD

**Issue by YOYONL89** [nutdotnet/WinNUT-Client#192]
Hello,

I'm trying to get my APC Back-UPS pro 900 connected but it seems to fail to show any value's.
The following screenshot is what i see:

![NUT](https://github.com/user-attachments/assets/d4440191-5eb9-418e-8b7c-c0a9b8e03318)

These are the variables coming from the List UPS Variables:

`APC Back-UPS 900Pro (Unknown/Unknown/Unknown)
battery.charge (Description unavailable) : 100
battery.charge.low (Description unavailable) : 50
battery.charge.warning (Description unavailable) : 50
battery.date (Description unavailable) : 2001/09/25
battery.mfr.date (Description unavailable) : 2024/06/03
battery.runtime (Description unavailable) : 2300
battery.runtime.low (Description unavailable) : 300
battery.type (Description unavailable) : PbAc
battery.voltage (Description unavailable) : 27.1
battery.voltage.nominal (Description unavailable) : 24.0
device.mfr (Description unavailable) : American Power Conversion
device.model (Description unavailable) : Back-UPS RS 900G
device.serial (Description unavailable) : 3B1231X30657
device.type (Description unavailable) : ups
driver.name (Description unavailable) : usbhid-ups
driver.parameter.pollfreq (Description unavailable) : 30
driver.parameter.pollinterval (Description unavailable) : 15
driver.parameter.port (Description unavailable) : auto
driver.parameter.productid (Description unavailable) : 0002
driver.parameter.serial (Description unavailable) : 3B1231X30657
driver.parameter.synchronous (Description unavailable) : auto
driver.parameter.vendorid (Description unavailable) : 051D
driver.version (Description unavailable) : 2.8.0
driver.version.data (Description unavailable) : APC HID 0.98
driver.version.internal (Description unavailable) : 0.47
driver.version.usb (Description unavailable) : libusb-1.0.26 (API: 0x1000109)
input.sensitivity (Description unavailable) : medium
input.transfer.high (Description unavailable) : 294
input.transfer.low (Description unavailable) : 176
input.voltage (Description unavailable) : 233.0
input.voltage.nominal (Description unavailable) : 230
ups.beeper.status (Description unavailable) : disabled
ups.delay.shutdown (Description unavailable) : 20
ups.firmware (Description unavailable) : 879.L4 .I
ups.firmware.aux (Description unavailable) : L4
ups.load (Description unavailable) : 26
ups.mfr (Description unavailable) : American Power Conversion
ups.mfr.date (Description unavailable) : 2012/08/04
ups.model (Description unavailable) : Back-UPS RS 900G
ups.productid (Description unavailable) : 0002
ups.realpower.nominal (Description unavailable) : 540
ups.serial (Description unavailable) : 3B1231X30657
ups.status (Description unavailable) : OL
ups.test.result (Description unavailable) : No test initiated
ups.timer.reboot (Description unavailable) : 0
ups.timer.shutdown (Description unavailable) : -1
ups.vendorid (Description unavailable) : 051d
`
This is the debug log:
`
7-11-2024 21:32:37 [12464, WinNUT]: Battery Status => Discharging
7-11-2024 21:32:38 [12464, UPS_Device]: Enter Retrieve_UPS_Datas
7-11-2024 21:32:38 [12464, UPS_Device]: battery.charge is not supported by server.
7-11-2024 21:32:38 [12464, UPS_Device]: Apply Fallback Value when retrieving battery.charge
7-11-2024 21:32:38 [12464, UPS_Device]: battery.voltage is not supported by server.
7-11-2024 21:32:38 [12464, UPS_Device]: Apply Fallback Value when retrieving battery.voltage
7-11-2024 21:32:38 [12464, UPS_Device]: battery.runtime is not supported by server.
7-11-2024 21:32:38 [12464, UPS_Device]: Apply Fallback Value when retrieving battery.runtime
7-11-2024 21:32:38 [12464, UPS_Device]: input.frequency is not supported by server.
7-11-2024 21:32:38 [12464, UPS_Device]: Apply Fallback Value when retrieving input.frequency
7-11-2024 21:32:38 [12464, UPS_Device]: input.voltage is not supported by server.
7-11-2024 21:32:38 [12464, UPS_Device]: Apply Fallback Value when retrieving input.voltage
7-11-2024 21:32:38 [12464, UPS_Device]: output.voltage is not supported by server.
7-11-2024 21:32:38 [12464, UPS_Device]: Apply Fallback Value when retrieving output.voltage
7-11-2024 21:32:38 [12464, UPS_Device]: ups.load is not supported by server.
7-11-2024 21:32:38 [12464, UPS_Device]: Apply Fallback Value when retrieving ups.load
7-11-2024 21:32:38 [12464, UPS_Device]: Unable to calculate UPS Batt_Charge: Batt_Voltage (-1) out of range.
7-11-2024 21:32:38 [12464, UPS_Device]: Unable to calculate battery runtime, missing UPS variables.
7-11-2024 21:32:38 [12464, UPS_Device]: Output_Voltage: -1, Batt_Voltage: -1, Batt_Capacity: -1, Batt_Charge: -1
7-11-2024 21:32:38 [12464, UPS_Device]: ups.status is not supported by server.
7-11-2024 21:32:38 [12464, UPS_Device]: Apply Fallback Value when retrieving ups.status
7-11-2024 21:32:38 [12464, UPS_Device]: UPS statuses have not changed since last update, skipping.
7-11-2024 21:32:38 [12464, WinNUT]: Updating UPS data for Form.
7-11-2024 21:32:38 [12464, WinNUT]: Updating battery icons based on charge percent: -1%
7-11-2024 21:32:38 [12464, WinNUT]: Update Dial
7-11-2024 21:32:38 [12464, WinNUT]: Update Icon
7-11-2024 21:32:38 [12464, WinNUT]: NotifyIcon Text => 
WinNUT Client - 2.3
Connected
On Battery (-1%)

7-11-2024 21:32:38 [12464, WinNUT]: Battery Status => Discharging
7-11-2024 21:32:38 [12464, Pref_Gui]: User clicked ViewLog button.
7-11-2024 21:32:38 [12464, Pref_Gui]: Opened UI window to log location.
`

Can anyone tell me what i'm doing wrong?

**Comment by gbakeman** [comment]
Hi there,

Thanks for the detailed issue report. Looking at the debug log, it seems that your NUT server is not providing any variables. I'd suggest restarting it as that sometimes fixes these issues, and if not you may need to pursue further troubleshooting in that regard. I'll transfer this to a discussion for now in case you want further assistance.
