### ISSUE TITLE
Battery Voltage wrong?

### ISSUE THREAD

**Issue by mpl1337** [nutdotnet/WinNUT-Client#202]
Hello, my client shows a Battery Voltage of 15V. Whats wrong here?

![image](https://github.com/user-attachments/assets/2feca968-c7e4-4b1f-a2a1-1321d371c63f)

![image](https://github.com/user-attachments/assets/e8463a2b-d40a-4f78-b347-987b2bb47635)

![image](https://github.com/user-attachments/assets/bc27c8ec-11db-4593-b296-602e38f49aed)
![image](https://github.com/user-attachments/assets/562b9dc3-b4c3-4479-abfc-84f8f0c12cfb)
![image](https://github.com/user-attachments/assets/7bc48a94-5d1c-4581-bfbf-5f65bfc07842)
![image](https://github.com/user-attachments/assets/c9730693-08dd-47e2-9564-f06ef62219c4)

**Comment by gbakeman** [comment]
Please see #136. Let me know if you think this is different.
