### ISSUE TITLE
PC not shutting down properly

### ISSUE THREAD

**Issue by MartinKurtz** [nutdotnet/WinNUT-Client#70]
I have recently had a power outage and my pc was on. During this i observed, that the UPS battery charge dropped below the 50% i specified to shut down my computer without the PC actually shutting down.

The charge got down to 38% and no shutdown was initiated.

I have however recently upgraded to a newer version of WinNUT, but i dont think youve done any work on that part of WinNUT since then.

![grafik](https://user-images.githubusercontent.com/108140017/209723491-1b4034b4-fd12-44f1-8f54-a74cf0a31018.png)
These are the settings used

**Comment by MartinKurtz** [comment]
Sadly testing isnt something i can do too often, as some devices that are on my UPS need to be running usually and i cant just shut them down quickly and power them back on, as they have pretty complex shutdown procedures and turning everything back on is a pain in the arse and takes a while, but whan i get a chance or there is a outage, i will let you know what i find with thew new version

**Comment by gbakeman** [comment]
This sounds like something that was fixed recently, but it would helpful if you could retest on the latest pre-release and capture logs to confirm that the issue is present. You don't need to shutdown your entire UPS to test this - you can set the percentage to something like 99% so only your PC powers off.

**Comment by MartinKurtz** [comment]
I set it to 100% and that did work within the 30 second window before things start shutting down, so it seems that this was fixed indeed
