### ISSUE TITLE
ModernUI

### ISSUE THREAD

**Issue by keepersdungeon** [nutdotnet/WinNUT-Client#77]
Hello is there a way to have a modern ui like here ?
https://winformgauge.codearteng.com

Thanks.

**Comment by gbakeman** [comment]
Hi @keepersdungeon,

Thank you for the suggestion. I don't think an overhaul like that is in the books for the current generation of WinNUT, but I plan on redesigning WinNUT in our new project, [Coco.Nut](https://github.com/nutdotnet/Coco.Nut). Modern indicators will definitely be a part of it. I recommend you follow the new project for news and updates, and also submit suggestions.
