### ISSUE TITLE
connect crash

### ISSUE THREAD

**Issue by yuhuanowo** [nutdotnet/WinNUT-Client#99]
something error when i connect to synology nas , can someone help me?

[CrashReport_2023-08-06T21.14.50.txt](https://github.com/nutdotnet/WinNUT-Client/files/12269676/CrashReport_2023-08-06T21.14.50.txt)

**Comment by yuhuanowo** [comment]
i reboot the server, it don't crash again

**Comment by gbakeman** [comment]
Hi @yuhuanowo , thank you for making the bug report. I'm reading the log because crashes should never happen, and it looks like maybe the encoding changed so I'm not able to read all of the information. If it happens again though, please reopen this report.
